export const INV_ACCELERATION_COEF = 200,
  WIDTH_RANGE_PER_LVL = 200,
  FOOD_STARTING_Y_POS = 50,
  DEFAULT_DROPS_PER_LVL = 20,
  DEFAULT_START_HP = 10,
  DEFAULT_FOOD_DROP_PERIOD = 100,
  DEFAULT_PLAYER_CATCH_RANGE = 50;
